# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Benchmark

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: coursier/cache-action@90c37294538be80a558fd665531fcdc2b467b475 # v8
      - run: ./mill benchmarks.compareFast
      - name: Add report to job summary
        run: cat out/benchmarks/compareFast.dest/fast-comparison.md >> "$GITHUB_STEP_SUMMARY"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: benchmark-comparison
          path: out/benchmarks/compareFast.dest/fast-comparison.md
