# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Dev Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Dev Build (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: coursier/cache-action@90c37294538be80a558fd665531fcdc2b467b475 # v8
      - run: ./mill devBuild
