# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Dev Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Mill Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v8
      - run: ./millw build
